apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: container-nginx
    image: nginx
    env:
      - name: USER
        valueFrom:
          configMapKeyRef:
            key: USER
            name: configmap-name
      - name: PASSWORD
        valueFrom:
          SecretKeyRef:
            key: PASSWORD
            name: secret-name
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
