version: "3.8"
services:
  nginx:
    build:
      context: ./nginx-app
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
  
  php:
    build:
      context: ./symfony-app
      dockerfile: Dockerfile.symfony
    depends_on:
      db:
        condition: service_healthy
    

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: exempledb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 30s
      retries: 1
      start_period: 10s
volumes:
  db-data: null

